[package]
name = "route53-dyndns"
version = "0.1.0"
authors = ["Daniel Henkel <daniel@henkel.tech>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
