on:
  push:
    branches:
      - '**'

name: Route53 DynDns

jobs:
  style:
    name: Style
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Format
        run: cargo fmt --all -- --check
      - name: Clippy
        run: cargo clippy --features "strict"
  test:
    name: Test
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Format
        run: cargo test
  build:
    name: Build & Push
    runs-on: ubuntu-latest
    needs:
      - style
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Authenticate
        run: ./.github/scripts/auth.sh
        env:
          USERNAME: ${{ secrets.DOCKER_USER }}
          PASSWORD: ${{ secrets.DOCKER_PW }}
      - name: Build Project
        run: cargo build --release --features "strict"
      - name: Build Docker Container
        run: docker build -t snapper/route53-dyndns:$GITHUB_RUN_ID .
      - name: Push Container
        run: |
          docker tag snapper/route53-dyndns:$GITHUB_RUN_ID snapper/route53-dyndns:latest
          docker push snapper/route53-dyndns:$GITHUB_RUN_ID
          docker push snapper/route53-dyndns:latest
