on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
      - feature/code_cov_integration

name: Route53 DynDns

jobs:
  style:
    name: Style
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Format
        run: cargo fmt --all -- --check
      - name: Clippy
        run: cargo clippy --features "strict"
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Code Coverage
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: |
          ./bin/create_test_bin.sh
          docker run --name coverage -i -v $(pwd):/root/route53 -e CODECOV_TOKEN=$CODECOV_TOKEN --security-opt seccomp=unconfined kcov/kcov bash -c "/root/route53/bin/generate_report.sh"
      # - name: Upload Coverage
      #   env:
      #     CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      #   run: bash <(curl -s https://codecov.io/bash)
  build:
    name: Build & Push
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE: snapper/route53-dyndns
    needs:
      - style
      - test
    steps:
      - uses: actions/checkout@master
      - name: Authenticate
        run: ./.github/scripts/auth.sh
        env:
          USERNAME: ${{ secrets.DOCKER_USER }}
          PASSWORD: ${{ secrets.DOCKER_PW }}
      - name: Build Project
        run: cargo build --release --features "strict"
      - name: Build Docker Container
        run: docker build -t $DOCKER_IMAGE:$GITHUB_RUN_ID .
      - name: Push Container
        # todo: only push when master
        # only push the container if it was build on master
        # if: github.ref == 'ref/head/master'
        run: |
          docker tag $DOCKER_IMAGE:$GITHUB_RUN_ID $DOCKER_IMAGE:latest
          docker push $DOCKER_IMAGE:$GITHUB_RUN_ID
          docker push $DOCKER_IMAGE:latest
